### ISSUE TITLE
New F360 Version broke Direct Name: RuntimeError: 2 : InternalValidationError : selecCmd  

### ISSUE THREAD

**Issue by patl1** [thomasa88/DirectName#5]
Direct Name seems to be broken in today's (4/3/23) version of F360

**Comment by thomasa88** [comment]
Hi, I can confirm the problem. I have not yet had time to look at it.

My initial suspicion was that the new Fusion version handles components/occurrences differently, making the problem only appear at top-level. But now I saw that it also appears when creating features within components.

**Comment by troyostrander** [comment]
Hi,

I am also getting error msg:

C:\Users\troyo\AppData\Roaming\Autodesk\ApplicationPlugins\DirectName.bundle\Contents\thomasa88lib\events.py
failed:


Traceback (most recent call last):

File
"C:\Users/troyo/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents\thomasa88lib\events.py",
line 142, in catcher

func(args)

File
"C:/Users/troyo/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py",
line 350, in rename_command_destroy_handler

ui_.activeSelections.clear()

File
"C:\Users/troyo/AppData/Local/Autodesk/webdeploy/production/df098dc22bdb0532c3884db0a2d6182c8f8678de/Api/Python/packages\adsk\core.py",
line 15655, in clear

return _core.Selections_clear(self)

RuntimeError: 2 : InternalValidationError : selecCmd


I miss DirectName already 😢

**Comment by Pixel48** [comment]
I'm also in pain, and glad to see that this is a known issue. I'll reference #7 here, since it refers same problem, and copy-paste my response from there
> I have encountered the same issue. In my understanding, it is related to a part of Fusion 360's API that is responsible for focusing text boxes and widgets, but I have not yet found a solution to this problem. It's already discussed in #6

**Comment by Pixel48** [comment]
## This is simple, stupid, ducktape-&-glue fix
It seems like this errors are generated probably because now Fusion 360 seems to handle widget refocusing by itself - omitting `ui_.activeSelections.clear()` in whole DirectName.py removes problem without braking plugin's functionality (at first glance at least).

![image](https://user-images.githubusercontent.com/42846410/230672821-2a7fabef-b145-4845-be04-fb91964fc158.png)


Could be good temporal fix, but definitely there's more API automation in this update, so this needs more refined solution in the long-run

For code, check out #8

**Comment by thomasa88** [comment]
Sorry for the late reply.

I guess the cleanest quick workaround is changing
`ui_.activeSelections.clear()`
to
`ui_.activeSelections.all = adsk.core.ObjectCollection.create()`

However, the underlying problem seems to be that (not all) the selections in `focusChanged()` are no longer "liked" by Fusion.

I'm thinking about just removing this selection logic - at least for now. The intention was to help the user to see what body or feature is being renamed, but right now it is doing more harm than help, and I'm not sure that it was that used that much anyway.

**Comment by thomasa88** [comment]
Please try the latest master. If it works, I'll pack it up in a release and send it to Autodesk for review.

**Comment by RafeAldridge** [comment]
Just did a very quick test using the latest master (just copied directname.py over existing) and it seems to works fine. I agree that I never really looked at the part being highlighted. A nice-to-have if it works in the future, but I'd rather have it working without, than not working at all. Thanks for a great plugin!

**Comment by patl1** [comment]
Thomas, worked for me. Thank you.

Pat

**Comment by thomasa88** [comment]
Thanks for confirming. I have now uploaded a new release in GitHub: https://github.com/thomasa88/DirectName/releases/tag/v1.2.2

Follow the instructions in the README to install from Github. Make sure to uninstall the version installed from the Autodesk store.
https://github.com/thomasa88/DirectName

I'm submitting the new version to the Autodesk store. It will likely show up in a few weeks.

**Comment by Jo-Dan** [comment]
@Scott216 just for reference %appdata% is just shorthand on windows for C:\Users\my_user_name\AppData\Roaming so the location is in fact the same.
